# Generated by Django 6.0.2 on 2026-03-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., KES, USD, EUR', max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('is_base_currency', models.BooleanField(default=False, help_text='Only ONE currency can be the base.')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(help_text='e.g., SALE, PO, RECEIPT, JOURNAL', max_length=50, unique=True)),
                ('prefix', models.CharField(max_length=20)),
                ('current_number', models.BigIntegerField(default=0)),
            ],
        ),
    ]
