# Generated by Django 6.0.4 on 2026-04-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="po_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated PO number",
                max_length=50,
                unique=True,
            ),
        ),
    ]
