# Generated by Django 6.0.2 on 2026-03-01 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='is_retail_storefront',
            field=models.BooleanField(default=False, help_text='Can POS cashiers sell directly from here?'),
        ),
    ]
