# Generated by Django 6.0.7 on 2026-07-25 21:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_warehouse_is_retail_storefront'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default buying cost per unit (KES)', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Alert when total stock falls to or below this', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Default selling price per unit (KES)', max_digits=12),
        ),
    ]
